spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/flyway_db
    username: postgres
    password: password
  flyway:
    locations: resources/db/migration